name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create EC2 instance
      id: create-ec2
      run: |
        instance=$(aws ec2 run-instances --image-id ami-0261755bbcb8c4a84 --instance-type t2.micro --subnet-id subnet-0da40012e9b28bb00 --security-group-ids sg-0ba21eab4b79e3dbe --query 'Instances[0].InstanceId' --output text)
        echo "::set-output name=instance_id::$instance"

    - name: Retrieve EC2 instance IP
      id: get-ec2-ip
      run: |
        ip=$(aws ec2 describe-instances --instance-ids ${{ steps.create-ec2.outputs.instance_id }} --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
        echo "::set-output name=ec2_ip::$ip"

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i C:\Users\Asus\Downloads\RAJ.pem ubuntu@${{ steps.get-ec2-ip.outputs.ec2_ip }} "cd /var/www/html && git pull"
